### ISSUE TITLE
Verify support for Python 3.9 (once it is more established)

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfunits#15]
Python 3.9 was released a few days ago (see e.g. [here](https://docs.python.org/3.9/whatsnew/3.9.html)). Though it is clearly early days for 3.9, to keep up-to-date with supported Python versions, we should soon check that everything works as it should on 3.9 as with 3.6 - 3.8 (I've just dropped 3.5 support as it is end-of-life as of last month), verify this via the Actions workflow, and document whether 3.9 is good to use.

To that aim, I have already tried adding in 3.9 to the Python version job matrix on our Actions CI workflow, since it is confirmed as being available for GH Actions (see [here](https://github.com/actions/virtual-environments/issues/1740#issuecomment-704287158)). Unfortunately it is failing on the miniconda step (see e.g. [this 3.9 job run output](https://github.com/NCAS-CMS/cfunits/runs/1221211934)), so it seems that one or both of the following are true (as also suggested [here](https://stackoverflow.com/questions/63216201/how-to-install-python3-9-with-conda)):

* an issue in installing 3.9 with conda, at least via the default channel;
* or (much more likely) dependencies don't yet support 3.9, so he environment can't be set up to support 3.9 regardless of our code.

There is a nice little [article here](https://pythonspeed.com/articles/switch-python-3.9/) discussing the switch to 3.9 and (see the final section) advising when it is sensible to consider 3.9 support. **Taking that advice which seems very sensible, we should review and verify support for 3.9 in around mid-December '20.**

For now, I will remove 3.9 jobs from the Actions workflow as they will fail and cancel all other jobs.

**Comment by davidhassell** [comment]
Reviewing mid December 2020 sounds good to me, too. Thanks.

**Comment by sadielbartholomew** [comment]
This one was resolved long ago, so closing...
