### ISSUE TITLE
cftime.utime removed from cftime 1.5.0

### ISSUE THREAD

**Issue by ScottWales** [NCAS-CMS/cfunits#25]
The new release 1.5.0 of cftime appears to have removed the class `cftime.utime`, used at https://github.com/NCAS-CMS/cfunits/blob/master/cfunits/units.py#L2591

From their changelog:

> * remove legacy `utime` class, and legacy `JulianDayFromDate` and `DateFromJulianDay` functions (replaced by `cftime.datetime.toordinal` and `cftime.datetime.fromordinal`).  PR #235.

**Comment by davidhassell** [comment]
Thanks for highlighting this, @ScottWales.

We'll be creating a PR to fix this and put a out a new version that requires `cftime>=1.5.0`, soon.

**Comment by davidhassell** [comment]
3.3.2 now available in PyPi

**Comment by davidhassell** [comment]
Oh, sorry, there was a problem with the upload to PyPI, but 3.3.2 is now most definitely there: https://pypi.org/project/cfunits/3.3.2
