### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfunits#42]
There [is ~2.5 weeks](https://endoflife.date/python) until the end of life for Python 3.6, so we should remove support for it here in cfunits, as we have done with cf-python and cfdm, unless there is a reason why 3.6 has been left supported here, @davidhassell (confirmation either way would be appreciated, so I can blitz 3.6 if it is OK to remove, thanks)?

**Comment by daniel-mohr** [comment]
Python 3.6 is still the default version in ubuntu:18.04. So, my solution would be similar to the [deprecated setting](https://github.com/NCAS-CMS/cfunits/blob/63d4c7d091c07924855017738024e9faa86c2689/.github/workflows/run-test-suite.yml#L218) and still run tests on Python 3.6. If it fails we will see that is it is no longer working; but before if it works we can see that it is still working.

Maybe you/we should also set ubuntu-18.04 as deprecated then. ?

**Comment by davidhassell** [comment]
Hi Sadie and Daniel,

I'm happy either way. I don't think that there are any 3.6 dependencies in the code, so marking it as "deprecated, might not work in the future" (or whatever the appropriate wording should be) would carry no maintenance overheads and would be fine by me.

**Comment by sadielbartholomew** [comment]
Thanks @daniel-mohr for the good point about Ubuntu 18.04, it sounds like your solution about setting it as deprecated in the workflow (if I understand correctly) would be most flexible and useful going forward, with thanks also to @davidhassell for the thoughts.

Daniel, I am quite busy on other tasks at the moment, so (even though I realise the solution is quite simple to do, to prevent excess context switching) if you wanted to do such a PR yourself to implement that, please go ahead! Else I can do it in about a week or so. (Only if you wanted to, though, no pressure.) Thanks either way.

**Comment by daniel-mohr** [comment]
@sadielbartholomew Seems to be a small task. Maybe end of the week I could try it.

**Comment by sadielbartholomew** [comment]
Thanks, that sounds great. If I do happen to get round to it earlier than that, I will comment here to ensure we don't duplicate effort.

**Comment by sadielbartholomew** [comment]
Aspects of the CI relating to dropping support for 3.6 were sorted in #43. I will now drop support formally via tweaking the `setup.py` and documentation, then this can be closed.

**Comment by sadielbartholomew** [comment]
Since we are still testing 3.6 on the CI, as per #43, we shouldn't change the packaging requirement from:

https://github.com/NCAS-CMS/cfunits/blob/995d8cbbba90990333b0f90dd8486b35a6edd6e6/setup.py#L141

(i.e. setting ">3.7" would make the jobs fail I presume) but I will make a note in the documentation to say that cfunits might still work with 3.6 but that use of 3.6 is discouraged. Then I think this can be closed.

**Comment by sadielbartholomew** [comment]
Closed (via the new and slightly different approach to directly removing support, as covered in the thread above) by 15c490939e2a5c76ccd747fa19829e3759f9f073 and 9dda854307777165d9b570ea13c1231338519fe6.

**Comment by sadielbartholomew** [comment]
Closed (via the new and slightly different approach to directly removing support, as covered in the thread above) by 15c490939e2a5c76ccd747fa19829e3759f9f073 and 9dda854307777165d9b570ea13c1231338519fe6.
