### ISSUE TITLE
(Document) rename of default branch from `master` to `main`

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfunits#49]
Quite self-explanatory, though see https://github.com/NCAS-CMS/cf-python/issues/190#issue-820557020 for some context if required.

**I am mostly opening this Issue to inform anyone that may contribute to the development of (or intend to in future) `cfunits` that the conversion has been completed and our default branch for the repository is now called `main`. Please adapt your *local* repository branch ecosystem accordingly to account for the fact that our root branch is now called `main` and not `master` (there is lots of guidance out there, but you can use e.g. [steps 1 and 2 of this list](https://jarv.is/notes/github-rename-master/)). Thanks.**

Note I have updated the repository settings so that our documentation is built from `main`, and also deleted `master` to reduce the possibility of people pushing to the wrong branch.

(I'll close the issue once I have updated our Contributing guidelines to refer to `main` instead, and adjusted our Actions workflows too.)

**Comment by daniel-mohr** [comment]
Also forks have to be adapted (e. g. regarding the linked guidance).

**Comment by sadielbartholomew** [comment]
> I'll close the issue once I have updated our Contributing guidelines to refer to main instead, and adjusted our Actions workflows too.

Done in new commits: ef844b42e911d0102c0043f9656f6a25086d6f76 to c1c18cbf7a416d5b6db7cbca8c2b1da022d2c5b4. No mention of `master` as a keyword across the codebase except for in documentation for older versions. Therefore this is good to close.
